#!/bin/bash
# author: nicephil@gmail.com
# new version: http://github.com/nicephil/homing.git
# Dependency: curl, feh, ocrad, sed/awk, bash, elinks 
# UTF-8 Encoding can generated from http://tool.chinaz.com/Tools/URLEncode.aspx
#Zhengzhou=%e9%83%91%e5%b7%9e
#Hangzhou=%e6%9d%ad%e5%b7%9e


#########################################################################

user_name="XXXX" #12306 username 
password="****" #password for 12306

train_date="2012-01-26" 
round_train_date="2012-01-18"

from_station_telecode="ZZF" # you can find it from station_name.list generated by this script later
from_station_name="%e9%83%91%e5%b7%9e" #Zhengzhou UTF-8 encode

to_station_telecode="HZH" # you can find it from station_name.list
to_station_name="%e6%9d%ad%e5%b7%9e" #Hangzhou UTF-8 encode

station_train_code="K658" # your trainnumber

passenger1_name="%e7%8e%8b%e4%b8%89" # Wang San
passenger1_id="411xxxxxxxxxxx" #id card
passenger1_phone="139xxxxxxxx" #mobile phone
passenger1_seat="3" #1 - yingzuo 2 - ruanwo 3 - yingwo  

passenger2_name="%e5%a8%84%e5%9b%9b" # Lou Si
passenger2_id="410XXXXXXXX" #id card
passenger2_phone="189XXXXXXX" #mobile phone
passenger2_seat="3" #1 - yingzuo 2 - ruanwo 3 - yingwo  

# the last form only supports two passengers, if need more, or less,
# have to modified the last form at line 233 
#passenger3_name="xxxxxxxxxxx" #name
#passenger3_id="411xxxxxxxxxxxx" #id card
#passenger3_phone="189xxxxxxxx" #mobile phone
#passenger3_seat="x" #1 - yingzuo 2 - ruanwo 3 - yingwo  





#########################################################################33

ua="Mozilla/4.0 (compatible; MSIE 6.0; Windows NT 5.0)"
cookie=cookie.txt
page=page.html
jpg=randcode.jpg
station_name_list=station_name.list
train_info_detail=train_info.detail



while [[ ! -e $cookie || $1 != "" ]]
do
rm -rvf "$cookie" "$page" "$jpg"
# get randcode picture
url="https://dynamic.12306.cn/otsweb/passCodeAction.do?rand=lrand"
refer="https://dynamic.12306.cn/otsweb/loginAction.do?method=init"
curl -k -A "$ua" -D "$cookie" -b "$cookie" -o "$jpg" -e "$refer" "$url"

feh "$jpg"&

randcode=`djpeg -greyscale -pnm "$jpg" | ocrad --charset=ascii --scale=60`
echo "randcode=${randcode}"
read -t 10 -p "Please correct rancode: " randcode1
echo ""
if [[ "$randcode1" != "" ]]
then
    randcode=$randcode1
fi
killall feh
echo "randcode=${randcode}"


# login system
url="https://dynamic.12306.cn/otsweb/loginAction.do?method=login"
form="loginUser.user_name=${user_name}&nameErrorFocus=&user.password=${password}&passwordErrorFocus=&randCode=${randcode}&randErrorFocus="
curl -k -L -A "$ua" -b "$cookie" -o $page -d "${form}" -e "$refer" "$url"
if (( $? != 0 ))
then
    exit -1
fi

grep "2012" $page
errcode=$?


if (( $errcode != 0 ))
then
    echo "=======>LOGIN FAILED"
    rm $cookie $page
    tail -n 20 $page
else
    echo "=======>LOGIN OK!"
    cp $cookie ${cookie}_bak
    break
fi
done


# station name list code
if [[ -e ${station_name_list} ]]
then
   echo "${station_name_list} is here already."
else
    refer="https://dynamic.12306.cn/otsweb/order/querySingleAction.do?method=init"
    url="https://dynamic.12306.cn/otsweb/js/common/station_name.js?version=2.1"
    curl -k -L -A "$ua" -b "$cookie" -G -o ${station_name_list} -e "$refer" "$url"
fi

#elinks ${station_name_list}
#exit


while (( 1 ))
do
# queryLeftTicket"
refer="https://dynamic.12306.cn/otsweb/order/querySingleAction.do?method=init"
url="https://dynamic.12306.cn/otsweb/order/querySingleAction.do?method=queryLeftTicket"
form="orderRequest.train_date=${train_date}&\
orderRequest.from_station_telecode=${from_station_telecode}&\
orderRequest.to_station_telecode=${to_station_telecode}&\
orderRequest.train_no=&trainPassType=QB&\
trainClass=QB%23D%23Z%23T%23K%23QT%23&\
includeStudent=00&\
seatTypeAndNum=&\
orderRequest.start_time_str=00%3A00--24%3A00"

curl -k -L -A "$ua" -b "$cookie" -G -d "$form" -o $page -e "$refer" "$url"

# get TainInfoDetail 
sed -n 's/\(getSelected\)/\n\1/gp' $page |  sed -n "s/^getSelected('\([^)']*\)').*$/\1/pg" > ${train_info_detail}_bak
cat ${train_info_detail}_bak
sed -n "/${station_train_code}/p" ${train_info_detail}_bak > ${train_info_detail}

lishi=`awk -F"#" '{print $2}' ${train_info_detail}`
start_time=`awk -F"#" '{print $3}' ${train_info_detail}`
trainno=`awk -F"#" '{print $4}' ${train_info_detail}`
end_time=`awk -F"#" '{print $7}' ${train_info_detail}`
ypInfoDetail=`awk -F"#" '{print $10}' ${train_info_detail}`

echo ""
echo "lishi=${lishi}"
echo "start_time=${start_time}"
echo "trainno=${trainno}"
echo "end_time=${end_time}"
echo "ypInfoDetail=${ypInfoDetail}"

if [[ $ypInfoDetail == "" ]]
then
    echo "the train you specified is wrong!!!"
    exit
fi

#elinks $page
#exit 


# submutOrderRequest
refer="https://dynamic.12306.cn/otsweb/order/querySingleAction.do?method=init"
url="https://dynamic.12306.cn/otsweb/order/querySingleAction.do?method=submutOrderRequest"

form="station_train_code=${station_train_code}&\
train_date=${train_date}&\
seattype_num=&\
from_station_telecode=${from_station_telecode}&\
to_station_telecode=${to_station_telecode}&\
include_student=00&\
from_station_telecode_name=${from_station_name}&\
to_station_telecode_name=${to_station_name}&\
round_train_date=${round_train_date}&\
round_start_time_str=00:00--24:00&\
single_round_type=1&\
train_pass_type=QB&\
train_class_arr=QB#D#Z#T#K#QT#&\
start_time_str=00:00--24:00&\
lishi=${lishi}&\
train_start_time=${start_time}&\
trainno=${trainno}&\
arrive_time=${end_time}&\
from_station_name=${from_station_name}&\
to_station_name=${to_station_name}&\
ypInfoDetail=${ypInfoDetail}"


curl -k -L -A "$ua" -b "$cookie" -d "$form" -o $page -e "$refer" "$url"

token=`sed -n '/TOKEN/p' $page | sed -n 's/^.*value="\([^ "]*\)".*$/\1/gp'`
echo "token=$token"

#elinks $page
#exit




# get randcode picture
url="https://dynamic.12306.cn/otsweb/passCodeAction.do?rand=randp"
refer="https://dynamic.12306.cn/otsweb/order/confirmPassengerAction.do?method=init"
curl -k -A "$ua" -b "$cookie" -o "$jpg" -e "$refer" "$url"

feh "$jpg"&

randcode=`djpeg -greyscale -pnm "$jpg" | ocrad --charset=ascii --scale=60`
echo "randcode=${randcode}"
read -t 10 -p "Please correct rancode: " randcode1
echo ""
if [[ "$randcode1" != "" ]]
then
    randcode=$randcode1
fi
killall feh
echo "randcode=${randcode}"


# confirmPassengerAction
refer="https://dynamic.12306.cn/otsweb/order/confirmPassengerAction.do?method=init"
url="https://dynamic.12306.cn/otsweb/order/confirmPassengerAction.do?method=confirmPassengerInfoSingle"

form="org.apache.struts.taglib.html.TOKEN=${token}&\
textfield=&\
checkbox0=0&\
checkbox1=1&\
orderRequest.train_date=${train_date}&\
orderRequest.train_no=${trainno}&\
orderRequest.station_train_code=${station_train_code}&\
orderRequest.from_station_telecode=${from_station_telecode}&\
orderRequest.to_station_telecode=${to_station_telecode}&\
orderRequest.seat_type_code=&\
orderRequest.ticket_type_order_num=&\
orderRequest.bed_level_order_num=000000000000000000000000000000&\
orderRequest.start_time=${start_time}&\
orderRequest.end_time=${end_time}&\
orderRequest.from_station_name=${from_station_name}&\
orderRequest.to_station_name=${to_station_name}&\
orderRequest.cancel_flag=1&\
orderRequest.id_mode=Y&\
passengerTickets=${passenger1_seat},1,${passenger1_name},1,${passenger1_id},${passenger1_phone},Y&\
oldPassengers=${passenger1_name},1,${passenger1_id}&\
passenger_1_seat=${passenger1_seat}&\
passenger_1_ticket=1&\
passenger_1_name=${passenger1_name}&\
passenger_1_cardtype=1&\
passenger_1_cardno=${passenger1_id}&\
passenger_1_mobileno=${passenger1_phone}&\
checkbox9=Y&\
passengerTickets=${passenger2_seat},1,${passenger2_name},1,${passenger2_id},${passenger2_phone},Y&\
oldPassengers=${passenger2_name},1,${passenger2_id}&\
passenger_2_seat=${passenger2_seat}&\
passenger_2_ticket=1&\
passenger_2_name=${passenger2_name}&\
passenger_2_cardtype=1&\
passenger_2_cardno=${passenger2_id}&\
passenger_2_mobileno=${passenger2_phone}&\
checkbox9=Y&\
oldPassengers=&\
checkbox9=Y&\
oldPassengers=&\
checkbox9=Y&\
oldPassengers=&\
checkbox9=Y&\
randCode=${randcode}&\
orderRequest.reserve_flag=A"

curl -k -L -A "$ua" -b "$cookie" -o $page -d "$form" -e "$refer" "$url"

#elinks $page
#exit
tail -n 20 $page
cp $page ${page}_bak
done

# commit
